name: Cypress API Tests

on:
  push:
    branches:
      - master  # Change this if you're using a different branch

jobs:
  cypress-run:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\AppData\Local\Cypress\Cache  # Cache only the Cypress binary
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Ensure Node.js is at least version 12 or higher

      - name: Install dependencies
        run: npm install  # Ensure a fresh install of dependencies

      - name: Install Cypress binary
        run: npx cypress install  # Ensure Cypress binary is installed

      - name: Run Cypress tests
        run: npx cypress run --reporter mochawesome  # Run Cypress tests

      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/*.html
